### ISSUE TITLE
Table widget throwing Nullpointer exception

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#49]
For the query **attributemonitor_generic_ri00**  on dashboard cluster the table widget. This has something to do with the generic query. Works for non-generic queries.

![image](https://cloud.githubusercontent.com/assets/1731313/8195894/1841cfbe-1454-11e5-8b8d-ea85dae396ac.png)

``` java
06-16-2015 18:13:32 ERROR [EditTableController] - Exception
java.lang.NullPointerException
    at org.hpccsystems.dashboard.services.impl.HPCCQueryServiceImpl.parseGenericQueryRequest(HPCCQueryServiceImpl.java:570)
    at org.hpccsystems.dashboard.services.impl.HPCCQueryServiceImpl.getGenericQueryRequestName(HPCCQueryServiceImpl.java:552)
    at org.hpccsystems.dashboard.services.impl.HPCCQueryServiceImpl.fetchGenericTableData(HPCCQueryServiceImpl.java:1411)
    at org.hpccsystems.dashboard.services.impl.HPCCQueryServiceImpl.fetchTableData(HPCCQueryServiceImpl.java:1237)
    at org.hpccsystems.dashboard.services.impl.HPCCServiceImpl.fetchTableData(HPCCServiceImpl.java:740)
    at org.hpccsystems.dashboard.controller.EditTableController$1.onEvent(EditTableController.java:205)
    at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:2746)
    at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2717)
    at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2658)
    at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
    at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1765)
    at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1550)
    at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1260)
    at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:603)
    at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:485)
    at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:494)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye 
This query response has different structure from actual generic queries.Handled both the queries

**Comment by dineshshetye** [comment]
Tested and Works
